# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - shinguakira

# A list of assignees, overrides reviewers if set
assignees:
  - shinguakira

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers
numberOfReviewers: 0

# A list of keywords to be skipped the process if PR title include it
skipKeywords:
  - wip
