name: OpenAI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - devin-develop

jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: OpenAI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          MODEL: gpt-4-turbo
          PROMPT: |
            You are an expert security-focused code reviewer for a React/Next.js portfolio website. Review the code changes and provide detailed, constructive feedback with a strong emphasis on security vulnerabilities.
            
            Focus on:
            1. CRITICAL: Security vulnerabilities (especially in email functionality, environment variables, and user inputs)
            2. Code quality and React/Next.js best practices
            3. Potential bugs or edge cases
            4. Performance considerations for React components
            5. Accessibility issues
            6. UI/UX improvements
            
            IMPORTANT: 
            - Prioritize finding and explaining security issues above all else
            - Specifically check for hardcoded credentials, unsafe eval(), command injection, XSS vulnerabilities
            - Be extremely thorough in your security analysis of any API routes or server-side code
            - Provide specific examples of how to fix each security issue you identify
            - Explain the potential consequences of each security vulnerability
            - Minimum response length should be 300 words with detailed security analysis
