name: OpenAI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: OpenAI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          MODEL: gpt-4
          PROMPT: |
            You are an expert code reviewer. Review the code changes and provide constructive feedback.
            Focus on:
            1. Code quality and best practices
            2. Potential bugs or edge cases
            3. Performance considerations
            4. Security concerns
            5. Accessibility issues
            
            Be specific and provide examples where possible. If the code looks good, say so.
