name: OpenAI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - devin-develop

jobs:
  openai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: OpenAI Code Review
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          MODEL: gpt-4
          PROMPT: |
            You are an expert code reviewer for a React/Next.js portfolio website. Review the code changes and provide detailed, constructive feedback.
            
            Focus on:
            1. Code quality and React/Next.js best practices
            2. Potential bugs or edge cases
            3. Performance considerations for React components
            4. Security concerns (especially for email functionality and environment variables)
            5. Accessibility issues
            6. UI/UX improvements
            
            IMPORTANT: 
            - Be thorough and detailed in your analysis
            - Provide specific examples and suggestions for improvement
            - Explain your reasoning for each suggestion
            - If you see security concerns with email implementation, highlight them
            - Even if the code looks good overall, suggest at least 2-3 improvements or considerations
            - Minimum response length should be 200 words with detailed analysis
